server:
  port: 5000
spring:
  main:
    allowBeanDefinitionOverriding: true
  profile:
    active: prod
  datasource: # todo: should set this data according to the RDS configuration
    url:
    username:
    password:
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            require: true
application:
  swagger:
    title: Web Shop API
    description: Documentation of Web Shop API
    version: 1.0.0
    terms-of-service-url:
    contact-name: Stefan Radojevic
    contact-url: https://github.com/Stefi99R
    contact-email: radojevic.stefan.sr@gmail.com
    licence:
    licence-url: