spring:
  profile:
    active: dev
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/web_shop
    username: stefan
    password: back@2022
  jpa:
    hibernate.ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: inviggotest@gmail.com
    password: Stefan@Inviggo456
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            require: true
application:
  swagger:
    title: Web-Shop API
    description: Documentation of Web-Shop API
    version: 1.0.0
    terms-of-service-url:
    contact-name: Stefan Radojevic
    contact-url: https://github.com/Stefi99R
    contact-email: radojevic.stefan.sr@gmail.com
    licence:
    licence-url: